# Generated by Django 5.1 on 2024-09-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Slug')),
                ('body', models.TextField(verbose_name='содержимое')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('public_sign', models.BooleanField(default=False, verbose_name='признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='счетчик просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['-created_at'],
            },
        ),
    ]
