# Generated by Django 5.1 on 2024-09-04 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                default=datetime.date(2001, 6, 23),
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
