# Generated by Django 5.1 on 2024-09-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Введите адрес", max_length=250, verbose_name="Адрес"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="Введите ИНН",
                        max_length=100,
                        null=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        help_text="Введите страну", max_length=50, verbose_name="Страна"
                    ),
                ),
            ],
        ),
    ]
