# Generated by Django 5.1 on 2024-10-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_number",
                    models.IntegerField(unique=True, verbose_name="номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название версии"
                    ),
                ),
                (
                    "current_version_flag",
                    models.BooleanField(verbose_name="признак текущей версии"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product",
                        to="catalog.product",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
                "ordering": ("version_number",),
            },
        ),
    ]
