# Generated by Django 5.1 on 2024-10-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="version",
            options={"verbose_name": "версия", "verbose_name_plural": "версии"},
        ),
    ]
