# Generated by Django 5.1 on 2024-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_version_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="version_name",
            field=models.CharField(max_length=100, verbose_name="название версии"),
        ),
        migrations.AlterField(
            model_name="version",
            name="version_number",
            field=models.IntegerField(verbose_name="номер версии"),
        ),
    ]
