# Generated by Django 4.2 on 2024-10-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-id",),
                "permissions": [
                    ("can_edit_description", "can edit description"),
                    ("can_edit_category", "can edit category"),
                    ("can_cancel_publication", "can cancel publication"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
